// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxREOBdMyAmd3vto4vCQkyOvHO5zqsdK4',
    appId: '1:386602394051:web:6418facbad5225b38bdd76',
    messagingSenderId: '386602394051',
    projectId: 'carpool-app--users',
    authDomain: 'carpool-app--users.firebaseapp.com',
    storageBucket: 'carpool-app--users.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYg0EnktduAn0fQlKQCVFlKcSpSohDPNA',
    appId: '1:386602394051:android:26c3b288e0cf327e8bdd76',
    messagingSenderId: '386602394051',
    projectId: 'carpool-app--users',
    storageBucket: 'carpool-app--users.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaDG80aLcW7KfxyCIY7m4P89Xwym9aNJI',
    appId: '1:386602394051:ios:2fca25652d4448738bdd76',
    messagingSenderId: '386602394051',
    projectId: 'carpool-app--users',
    storageBucket: 'carpool-app--users.appspot.com',
    iosBundleId: 'com.example.carPool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaDG80aLcW7KfxyCIY7m4P89Xwym9aNJI',
    appId: '1:386602394051:ios:4edc1c1c4a86c0d08bdd76',
    messagingSenderId: '386602394051',
    projectId: 'carpool-app--users',
    storageBucket: 'carpool-app--users.appspot.com',
    iosBundleId: 'com.example.carPool.RunnerTests',
  );
}
